name: opentrons
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.4=haa95532_0
  - expat=2.7.3=h9214b88_0
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - aionotify==0.3.1
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - click==8.3.1
      - colorama==0.4.6
      - exceptiongroup==1.3.1
      - idna==3.11
      - jsonschema==4.17.3
      - numpy==1.26.4
      - opentrons==8.7.0
      - opentrons-shared-data==8.7.0
      - packaging==25.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydantic-settings==2.12.0
      - pyrsistent==0.20.0
      - pyserial==3.5
      - pyside6==6.10.1
      - pyside6-addons==6.10.1
      - pyside6-essentials==6.10.1
      - python-dotenv==1.2.1
      - pyusb==1.2.1
      - shiboken6==6.10.1
      - sniffio==1.3.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
